"""
Django settings for ArakisSayra project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-i(!kp*wcc8a)8p7(@ng(x4ulj-!9y=00q3p&=%t34brfqx@#q(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='arakissayra.ir,www.arakissayra.ir,arakissayra.com,www.arakissayra.com', cast=Csv())

# Application definition

INSTALLED_APPS = [

    # default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sitemaps',
    # packages
    'django_jalali',
    'modeltranslation',
    # apps
    'core',
    'products',
    'blog',
    'mptt',

]
JALALI_SETTINGS = {
    # JavaScript static files for the admin Jalali date widget
    "ADMIN_JS_STATIC_FILES": [
        "admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js",
        "admin/jquery.ui.datepicker.jalali/scripts/calendar.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js",
        "admin/main.js",
    ],
    # CSS static files for the admin Jalali date widget
    "ADMIN_CSS_STATIC_FILES": {
        "all": [
            "admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css",
            "admin/css/main.css",
        ]
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ArakisSayra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'contex_processors.contex_processors.site_info',
                'contex_processors.contex_processors.categories_context',
            ],
        },
    },
]

WSGI_APPLICATION = "ArakisSayra.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ========================================
# SQLite database settings (for development)
# ========================================
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# ========================================
# MySQL database settings (for production)
# ========================================
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='arakissa_db'),
        'USER': config('DB_USER', default='arakissa_user'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        # 'OPTIONS': {
        #     'charset': 'utf8mb4',
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"
LANGUAGES = [
    ('fa', 'Persian'),
    ('en', 'English'),
]
USE_I18N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
TIME_ZONE = 'UTC'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ========================================
# Local development settings
# ========================================
# STATIC_URL = "/static/"                     # URL prefix for static files
# STATICFILES_DIRS = [BASE_DIR / "static"]    # Project and app static files
# STATIC_ROOT = BASE_DIR / "staticfiles"      # Directory collected by collectstatic
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"             # User uploaded files

# ========================================
# Production settings
# ========================================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]               # Source static files directory
STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / "staticfiles"))  # Collected static files on production server
MEDIA_URL = "/media/"
MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / "media"))          # User uploaded files on production server

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
