"""
Django settings for ArakisSayra project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i(!kp*wcc8a)8p7(@ng(x4ulj-!9y=00q3p&=%t34brfqx@#q("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['arakissayra.ir', 'www.arakissayra.ir', 'arakissayra.com', 'www.arakissayra.com', "localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [

    # default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sitemaps',
    # packages
    'django_jalali',
    'modeltranslation',
    # apps
    'core',
    'products',
    'blog',
    'mptt',

]
JALALI_SETTINGS = {
    # JavaScript static files for the admin Jalali date widget
    "ADMIN_JS_STATIC_FILES": [
        "admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js",
        "admin/jquery.ui.datepicker.jalali/scripts/calendar.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js",
        "admin/main.js",
    ],
    # CSS static files for the admin Jalali date widget
    "ADMIN_CSS_STATIC_FILES": {
        "all": [
            "admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css",
            "admin/css/main.css",
        ]
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "core.force_farsi_middleware.ForceFarsiMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ArakisSayra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'contex_processors.contex_processors.site_info',
                'contex_processors.contex_processors.categories_context',
            ],
        },
    },
]

WSGI_APPLICATION = "ArakisSayra.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ========================================
# تنظیمات دیتابیس برای Development (SQLite)
# ========================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ========================================
# تنظیمات دیتابیس برای Production (PostgreSQL)
# برای فعال کردن در production:
# 1. کد SQLite بالا را comment کنید
# 2. کد PostgreSQL پایین را uncomment کنید
# 3. اطلاعات دیتابیس (NAME, USER, PASSWORD, HOST) را تنظیم کنید
# 4. پکیج psycopg2-binary را نصب کنید: pip install psycopg2-binary
# ========================================
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'arakissa_db',              # نام دیتابیس
#         'USER': 'arakissa_user',            # کاربر دیتابیس
#         'PASSWORD': 'your_password_here',   # رمز عبور
#         'HOST': 'localhost',                # آدرس سرور (معمولاً localhost)
#         'PORT': '5432',                     # پورت PostgreSQL (پیش‌فرض 5432)
#         'OPTIONS': {
#             'charset': 'utf8',
#         },
#     }
# }

# ========================================
# تنظیمات قدیمی MySQL (برای مرجع)
# ========================================
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'arakissa_parsa',       
#         'USER': 'arakissa_parsa',
#         'PASSWORD': 'Hamed1385@',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#             'init_command': "SET NAMES 'utf8mb4'"
#          }
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"
LANGUAGES = [
    ('fa', 'Persian'),
    ('en', 'English'),
]
USE_I18N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
TIME_ZONE = 'UTC'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#my pg:
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]
# MEDIA_URL = "/media/"
# MEDIA_ROOT = "/home/arakissa/public_html/media"
# STATIC_ROOT = "/home/arakissa/public_html/static"

#local:
STATIC_URL = "/static/"                     # همیشه با / شروع بشه
STATICFILES_DIRS = [BASE_DIR / "static"]    # فایل‌های استاتیک پروژه و اپ‌ها
STATIC_ROOT = BASE_DIR / "staticfiles"      # مسیر جمع‌آوری‌شده توسط collectstatic
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"             # فایل‌های آپلود شده کاربر

#production:
# STATIC_URL = "/static/"
# STATICFILES_DIRS = []                        # فقط collectstatic مسیر STATIC_ROOT رو استفاده می‌کنه
# STATIC_ROOT = "/home/arakissa/public_html/static"   # مسیر نهایی استاتیک روی هاست
# MEDIA_URL = "/media/"
# MEDIA_ROOT = "/home/arakissa/public_html/media"     # مسیر آپلود کاربران روی هاست

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
