# Generated by Django 5.2 on 2025-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'پیام دریافت شده',
                'verbose_name_plural': 'پیام های دریافت شده',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=20, verbose_name='شماره تماس ۱')),
                ('phone_number2', models.CharField(max_length=20, verbose_name='شماره تماس ۲')),
                ('phone_number3', models.CharField(max_length=20, verbose_name='شماره تماس ۳')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('address_fa', models.TextField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('address_en', models.TextField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('about_text_fa', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('about_text_en', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر درباره ما')),
                ('work_hour1', models.CharField(blank=True, max_length=255, null=True)),
                ('work_hour2', models.CharField(blank=True, max_length=255, null=True)),
                ('work_hour3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'اطلاعات وبسایت',
                'verbose_name_plural': 'اطلاعات وبسایت',
            },
        ),
    ]
