# Generated by Django 5.2 on 2025-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteinfo_work_hour1_en_siteinfo_work_hour1_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
