# Generated by Django 5.2 on 2025-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteinfo_instagram_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='📐 سایز بهینه: 1920×960 پیکسل | نسبت: 2:1 (Landscape) | حداکثر حجم: 500KB | عناصر مهم را در مرکز قرار دهید', upload_to='banners/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about_image',
            field=models.ImageField(blank=True, help_text='📐 سایز بهینه: 800×600 پیکسل | نسبت: 4:3 | حداکثر حجم: 300KB', null=True, upload_to='about/', verbose_name='تصویر درباره ما'),
        ),
    ]
