# Generated by Django 5.2 on 2025-07-31 10:11

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('created_time', models.TimeField(auto_now_add=True, null=True, verbose_name='ساعت ایجاد')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/news')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر شاخص')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('created_time', models.TimeField(auto_now_add=True, null=True, verbose_name='ساعت ایجاد')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(blank=True, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
    ]
