# Generated by Django 5.2 on 2025-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
