# Generated by Django 5.2 on 2025-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_category_name_en_remove_category_name_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 سایز بهینه: 900×585 پیکسل | نسبت: 3:2 (Landscape) | حداکثر حجم: 300KB', null=True, upload_to='blog/news', verbose_name='تصویر خبر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 سایز بهینه: 900×585 پیکسل | نسبت: 3:2 (Landscape) | حداکثر حجم: 300KB', null=True, upload_to='blog/', verbose_name='تصویر شاخص'),
        ),
    ]
