# Generated by Django 5.2 on 2025-07-31 10:11

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fa', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('short_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='اندازه')),
                ('container_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی')),
                ('container_type_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی')),
                ('container_type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی')),
                ('attributes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویژگی\u200cها')),
                ('attributes_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویژگی\u200cها')),
                ('attributes_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویژگی\u200cها')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='تصویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
