# Generated by Django 5.2 on 2025-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='📐 سایز بهینه: 1000×1000 پیکسل | نسبت: 1:1 (مربع) | حداکثر حجم: 200KB | پس\u200cزمینه سفید یا شفاف', null=True, upload_to='products', verbose_name='تصویر محصول'),
        ),
    ]
